// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Username     string           `json:"username"`
	DisplayName  string           `json:"display_name"`
	Password     []byte           `json:"password"`
	PasswordSalt []byte           `json:"password_salt"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	LastLoggedIn pgtype.Timestamp `json:"last_logged_in"`
}
