// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID           pgtype.UUID      `json:"id"`
	Name         pgtype.Text      `json:"name"`
	Email        pgtype.Text      `json:"email"`
	Password     pgtype.Text      `json:"password"`
	PasswordSalt pgtype.Text      `json:"password_salt"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}
