// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    user_id, username, display_name, password, password_salt, created_at, updated_at, last_logged_in
) VALUES (
    gen_random_uuid(), $1, $2, $3, $4, $5, $6, NULL
) RETURNING pvt_id, user_id, username, display_name, password, password_salt, created_at, updated_at, last_logged_in
`

type CreateUserParams struct {
	Username     string    `json:"username"`
	DisplayName  string    `json:"display_name"`
	Password     []byte    `json:"password"`
	PasswordSalt []byte    `json:"password_salt"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.DisplayName,
		arg.Password,
		arg.PasswordSalt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.PvtID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Password,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoggedIn,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT pvt_id, user_id, username, display_name, password, password_salt, created_at, updated_at, last_logged_in FROM users WHERE username = $1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i User
	err := row.Scan(
		&i.PvtID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Password,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoggedIn,
	)
	return i, err
}

const getUserByUuid = `-- name: GetUserByUuid :one
SELECT pvt_id, user_id, username, display_name, password, password_salt, created_at, updated_at, last_logged_in FROM users WHERE user_id = $1
`

func (q *Queries) GetUserByUuid(ctx context.Context, userID pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUuid, userID)
	var i User
	err := row.Scan(
		&i.PvtID,
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.Password,
		&i.PasswordSalt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoggedIn,
	)
	return i, err
}
